online-mode=false
spawn-protection=0
difficulty=normal
max-players=20
motd=SMP Server
view-distance=10
simulation-distance=8
server-port=25565
enable-rcon=true
rcon.port=25575
rcon.password=rcon_smp_2026
white-list=false
pvp=true
